services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app/images:/app/app/images
      - ./app/questionnaires:/app/app/questionnaires
      - ./app/results:/app/app/results
    environment:
      - NODE_ENV=production
